const WHATSAPP_NUMBER='919999999999';
const body=document.body,loader=document.getElementById('loader'),beat=document.getElementById('beatCount'),header=document.getElementById('header'),menuBtn=document.getElementById('menuBtn'),mobileMenu=document.getElementById('mobileMenu');
let count=1;const beatTimer=setInterval(()=>{count++;beat.textContent=`0${Math.min(count,3)}`;if(count===3)clearInterval(beatTimer)},520);
window.addEventListener('load',()=>{setTimeout(()=>loader.classList.add('reveal-out'),1650);setTimeout(()=>loader.classList.add('done'),2780)});
window.addEventListener('scroll',()=>header.classList.toggle('scrolled',scrollY>28),{passive:true});
function menu(open){mobileMenu.classList.toggle('open',open);mobileMenu.setAttribute('aria-hidden',String(!open));body.classList.toggle('locked',open)}
menuBtn.addEventListener('click',()=>menu(!mobileMenu.classList.contains('open')));mobileMenu.querySelectorAll('a,button').forEach(x=>x.addEventListener('click',()=>menu(false)));
const observer=new IntersectionObserver((entries,o)=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');o.unobserve(e.target)}}),{threshold:.14,rootMargin:'0px 0px -40px'});document.querySelectorAll('.reveal').forEach((x,i)=>{x.style.transitionDelay=`${Math.min((i%3)*75,150)}ms`;observer.observe(x)});
const formatImage=document.getElementById('formatImage'),formatNumber=document.getElementById('formatNumber'),imageWrap=document.querySelector('.format-image');document.querySelectorAll('.format-option').forEach(btn=>btn.addEventListener('click',()=>{if(btn.classList.contains('is-active'))return;document.querySelectorAll('.format-option').forEach(x=>x.classList.remove('is-active'));btn.classList.add('is-active');imageWrap.classList.add('changing');setTimeout(()=>{formatImage.src=btn.dataset.image;formatNumber.textContent=`${btn.dataset.number} / PERFORMANCE FORMAT`;imageWrap.classList.remove('changing')},220)}));
const enquiry=document.getElementById('enquiry'),form=document.getElementById('enquiryForm'),steps=[...document.querySelectorAll('.step')],counter=document.getElementById('stepCounter'),bar=document.getElementById('progressBar'),back=document.getElementById('backBtn'),next=document.getElementById('nextBtn'),submit=document.getElementById('submitBtn'),error=document.getElementById('formError'),success=document.getElementById('success'),wa=document.getElementById('whatsappLink');let step=0;
function openEnquiry(){enquiry.classList.add('open');enquiry.setAttribute('aria-hidden','false');body.classList.add('locked')}
function closeEnquiry(){enquiry.classList.remove('open');enquiry.setAttribute('aria-hidden','true');body.classList.remove('locked')}
document.querySelectorAll('.js-enquire').forEach(x=>x.addEventListener('click',openEnquiry));document.querySelectorAll('[data-close]').forEach(x=>x.addEventListener('click',closeEnquiry));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeEnquiry()});
function show(i){step=i;steps.forEach((x,n)=>x.classList.toggle('is-active',n===i));counter.textContent=`0${i+1} / 0${steps.length}`;bar.style.width=`${((i+1)/steps.length)*100}%`;back.classList.toggle('show',i>0);next.style.display=i===steps.length-1?'none':'inline-flex';submit.classList.toggle('show',i===steps.length-1);error.textContent=''}
function validate(){const area=steps[step];for(const field of area.querySelectorAll('[required]')){if(field.type==='radio'){if(!area.querySelector(`input[name="${field.name}"]:checked`))return'Please select one option before continuing.'}else if(!field.value.trim()){field.focus();return'Please complete the required fields before continuing.'}else if(!field.checkValidity()){field.focus();return'Please enter valid information.'}}return''}
next.addEventListener('click',()=>{const msg=validate();if(msg)return error.textContent=msg;show(Math.min(step+1,steps.length-1))});back.addEventListener('click',()=>show(Math.max(step-1,0)));
form.addEventListener('submit',e=>{e.preventDefault();const issue=validate();if(issue)return error.textContent=issue;const d=Object.fromEntries(new FormData(form).entries());const message=['Hi Dhruvit, I would like to check availability for an event.','',`Event: ${d.eventType||'-'}`,`Date: ${d.eventDate||'-'}`,`City: ${d.city||'-'}`,`Performance: ${d.format||'-'}`,`Name: ${d.name||'-'}`,`Phone: ${d.phone||'-'}`,`Note: ${d.note||'None'}`,'','Sent from the portfolio website.'].join('\n');wa.href=`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(message)}`;form.hidden=true;success.hidden=false});show(0);
